[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
name = "rust-gb"
version = "0.1.0"

[dependencies]
bit_range = "0.1.0"
byteorder = "0.4.2"
monster = "0.1.18"
unborrow = "0.1.0"
custom_derive = "0.1.4"
conv = "0.3.1"
